flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length

class CreatePost(FlaskForm):
	title = StringField(
		'Title',
		validators=[
			DataRequired(),
			Length(min=1, max=50)
		])
	content = TextAreaField(
		'Content',
		validators=[
			DataRequired(),
			Length(min=1, max=500)
		])
	submit = SubmitField('Create')


class CreateComment(FlaskForm):
	content = TextAreaField(
        'Content',
		validators=[
			DataRequired(),
			Length(min=1, max=500)
		])
	submit = SubmitField('Send')

flaskblog/main/routes.py
from flask import render_template, Blueprint
from flaskblog.posts.utils import render_home_pg

main = Blueprint('main', __name__)

@main.route("/", methods=["GET", "POST"])
@main.route("/home", methods=["GET", "POST"])
def home():
    return render_home_pg()

@main.route("/about")
def about():
    return render_template("about_page.html")

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint)
from flask.wrappers import Response
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Comment
from flaskblog.posts.forms import CreatePost, CreateComment
from flaskblog.posts.utils import post_logic, parse_params 

posts = Blueprint('posts', __name__)

@posts.route("/new_post", methods=["GET", "POST"])
@login_required
def new_post():
    form = CreatePost()
    if form.validate_on_submit():
        post = Post(
                title=form.title.data, 
                content=form.content.data, 
                author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Post Created", "success")
        return redirect(url_for('main.home'))
    return render_template("form_full_page.html", title="Create Post", form=form)

@posts.route("/post/<int:post_id>", methods=["GET", "POST"])
def post_page(post_id):
    post = Post.query.get(post_id)
    post_or_redir = post_logic(post)
    if isinstance(post_or_redir, Response):
        return post_or_redir
    return render_template('post_page.html', title=post.title, post=post_or_redir)

@posts.route("/post/<int:post_id>/comments", methods=["GET", "POST"])
def post_comments_page(post_id):
    page = int(parse_params(request.args)['page'])
    post = Post.query.get(post_id)
    comments = Comment.query.filter_by(post_id=post.id).paginate(page=page, per_page=5)
    return render_template('comments_page.html', comments=comments, page=page, pages=comments.pages, post_id=post_id)

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import login_manager
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateUser)
from flaskblog.users.utils import save_picture
from flaskblog.posts.utils import post_logic
from flask.wrappers import Response


users = Blueprint('users', __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(
                username=form.username.data,
                email=form.email.data,
                password=form.password.data
                )
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('form_full_page.html', title="Register", form=form)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.verify_pw(form.password.data):
            login_user(user)
            return redirect(url_for('main.home'))
        else:
            flash('unsuccessful login', 'danger')
    return render_template('form_full_page.html', title="Auth", form=form)

@users.route("/logout", methods=["GET", "POST"])
def logout():
    logout_user()
    return redirect(url_for('main.home'))
        
@users.route("/edit_profile", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = UpdateUser()
    if form.validate_on_submit():
        if form.picture.data:
            picture_name = save_picture(form.picture.data)
            current_user.avatar = picture_name
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.description = form.description.data
        db.session.commit()
        flash('your account has been updated!', 'success')
        return redirect('/user/' + current_user.username)
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.description.data = current_user.description  
    posts = Post.query.filter_by(user_id=current_user.id)
    image_file = url_for('static', filename='profile_pics/' + current_user.avatar)
    return render_template("user_edit_page.html", title="Edit profile", posts=posts, image_file=image_file, form=form)

@users.route("/user/<username>", methods=["GET", "POST"])
def user_page(username):
    user = User.query.filter_by(username=username).first() 
    image_file = url_for('static', filename='profile_pics/' + user.avatar)
    posts = user.posts
    post_lst = []
    for post in posts:
        post_or_redir = post_logic(post)
        if isinstance(post_or_redir, Response):
            return post_or_redir
        post_lst.append(post_or_redir)
    return render_template(
                "user_page.html",
                title=username, 
                user=user, 
                posts=post_lst,
                image_file=image_file, 
                is_loged=current_user.is_authenticated
                )

flaskblog/templates/includes/comment.html
<div class="flex">
	<img class="h-12 w-12 object-cover rounded-md" src="{{ url_for('static', filename='profile_pics/' + comment.author.avatar) }}">
	<div class="w-full pl-4">
		<div class="flex border-b-2 border-gray-300">
			<a class="flex-1 text-l font-bold text-sky-500" href="user/{{ comment.author.username }}">{{ comment.author.username}}</a>
			<span class="text-gray-500">{{ comment.date_posted.strftime("%d-%m-%Y %H:%M") }}</span>
		</div>
		<p class="">{{ comment.content }}</>
	</div>
</div>

flaskblog/templates/includes/comment_pgtn_btns.html
{% if pages != 1 %}
<div id="page_buttons" class="flex gap-4">
{% if page != 1 %}
<button class="border-2 border-gray-200 text-sky-400 hover:cursor-pointer w-min h-10 items-center flex px-6" onclick="button_page({{post_id}}, -1)">
	prev_page
</button>
{% endif %}
{% if pages > 1 and page != pages %}
<button class="border-2 border-gray-200 text-sky-400 hover:cursor-pointer w-min h-10 items-center flex px-6" onclick="button_page({{post_id}}, 1)">
	next_page
</button>
{% endif %}
</div>
{% endif %}

flaskblog/templates/includes/comment_pgtn_logic.html
<script>
const map = new Map();
function get_comments(post_id) {
  var xhttp = new XMLHttpRequest();
	xhttp.onreadystatechange = function() {
	  if (this.readyState == 4 && this.status == 200) {
			let cont = document.getElementById("comment-block-"+post_id);
			cont.innerHTML = xhttp.responseText;
			cont.innerHTML = cont.getElementsByTagName('section')[0].children[0].innerHTML;
				}};
    xhttp.open('GET', "/post/"+post_id+"/comments"+"?page="+map.get(post_id), true);
    xhttp.send();
};
function hide_comments(post_id) {
	document.getElementById('comment-wrapper-'+post_id).classList.toggle('hidden');
};
function button_page(post_id, delta) {
	let page = map.get(post_id);
	if ( page ) {
		page = page + delta;
	} else {
		page = 2;
	};
	map.set(post_id, page);
	get_comments(post_id, page);
};
</script>

flaskblog/templates/includes/header.html
<header class="w-full bg-gray-300">
	<nav class="container mx-auto h-16 flex items-center [&>*]:mr-12 hover:[&>*]:text-sky-400">
		<a class="text-2xl font-bold" href="{{ url_for('main.home') }}">home</a>
		<a class="text-2xl font-bold" href="{{ url_for('main.about') }}">about</a>
		{% if current_user.is_authenticated %}
			<a class="text-2xl font-bold" href="/user/{{ current_user.username }}">my page</a>
			<a class="text-2xl font-bold" href="{{ url_for('posts.new_post') }}">create post</a>
			<a class="text-2xl font-bold" href="{{ url_for('users.logout') }}">logout</a>
		{% else %}
		<a class="text-2xl font-bold" href="{{ url_for('users.login') }}">login</a>
		<a class="text-2xl font-bold" href="{{ url_for('users.register') }}">register</a>
		{% endif %}
	</nav>
</header>

flaskblog/templates/includes/parameters_logic.html
<script>
function set_params(name, val) {
  var params = new URLSearchParams(window.location.search);
  params.set(name, val);
	if (name != 'page') {
		params.set('page', '1');
	}
  window.location.search = params.toString();
}
</script>

flaskblog/templates/includes/post.html
<div id="post_{{ post.id }}" class="w-1/2 border-2 border-gray-300 p-6">
	<div class="flex">
		<img class="h-16 w-16 object-cover rounded-md" src="{{ url_for('static', filename='profile_pics/' + post.author.avatar) }}">
		<div class="w-full pl-4">
			<div class="flex border-b-2 border-gray-300">
				<a class="flex-1 text-l font-bold text-sky-500" href="/user/{{ post.author.username }}">{{ post.author.username}}</a>
				<span class="text-gray-500">{{ post.date_posted.strftime("%d-%m-%Y %H:%M") }}</span>
			</div>
			<h2 class="text-3xl pt-1 break-all"><a href="/post/{{ post.id }}">{{ post.title }}</a></h2>
		</div>
	</div>
	<p class="break-all py-4">{{ post.content }}</p>
	<div class="flex">
		<div class="flex">
			{% if current_user.is_authenticated %}
				<button onclick="set_params('like', {{ post.id }})">
				{% if current_user in post.likes %}
					<svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="M0 0h24v24H0z"></path><path d="M16 4a5.95 5.95 0 0 0-3.89 1.7l-.12.11-.12-.11A5.96 5.96 0 0 0 7.73 4 5.73 5.73 0 0 0 2 9.72c0 3.08 1.13 4.55 6.18 8.54l2.69 2.1c.66.52 1.6.52 2.26 0l2.36-1.84.94-.74c4.53-3.64 5.57-5.1 5.57-8.06A5.73 5.73 0 0 0 16.27 4zm.27 1.8a3.93 3.93 0 0 1 3.93 3.92v.3c-.08 2.15-1.07 3.33-5.51 6.84l-2.67 2.08a.04.04 0 0 1-.04 0L9.6 17.1l-.87-.7C4.6 13.1 3.8 11.98 3.8 9.73A3.93 3.93 0 0 1 7.73 5.8c1.34 0 2.51.62 3.57 1.92a.9.9 0 0 0 1.4-.01c1.04-1.3 2.2-1.91 3.57-1.91z" fill="red" fill-rule="nonzero"></path></g>
					</svg>
				{% else %}
					<svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="M0 0h24v24H0z"></path><path d="M16 4a5.95 5.95 0 0 0-3.89 1.7l-.12.11-.12-.11A5.96 5.96 0 0 0 7.73 4 5.73 5.73 0 0 0 2 9.72c0 3.08 1.13 4.55 6.18 8.54l2.69 2.1c.66.52 1.6.52 2.26 0l2.36-1.84.94-.74c4.53-3.64 5.57-5.1 5.57-8.06A5.73 5.73 0 0 0 16.27 4zm.27 1.8a3.93 3.93 0 0 1 3.93 3.92v.3c-.08 2.15-1.07 3.33-5.51 6.84l-2.67 2.08a.04.04 0 0 1-.04 0L9.6 17.1l-.87-.7C4.6 13.1 3.8 11.98 3.8 9.73A3.93 3.93 0 0 1 7.73 5.8c1.34 0 2.51.62 3.57 1.92a.9.9 0 0 0 1.4-.01c1.04-1.3 2.2-1.91 3.57-1.91z" fill="currentColor" fill-rule="nonzero"></path></g>
					</svg>
				{% endif %}
			{% else %}
				<button>
				<a href="/login">
				<svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="M0 0h24v24H0z"></path><path d="M16 4a5.95 5.95 0 0 0-3.89 1.7l-.12.11-.12-.11A5.96 5.96 0 0 0 7.73 4 5.73 5.73 0 0 0 2 9.72c0 3.08 1.13 4.55 6.18 8.54l2.69 2.1c.66.52 1.6.52 2.26 0l2.36-1.84.94-.74c4.53-3.64 5.57-5.1 5.57-8.06A5.73 5.73 0 0 0 16.27 4zm.27 1.8a3.93 3.93 0 0 1 3.93 3.92v.3c-.08 2.15-1.07 3.33-5.51 6.84l-2.67 2.08a.04.04 0 0 1-.04 0L9.6 17.1l-.87-.7C4.6 13.1 3.8 11.98 3.8 9.73A3.93 3.93 0 0 1 7.73 5.8c1.34 0 2.51.62 3.57 1.92a.9.9 0 0 0 1.4-.01c1.04-1.3 2.2-1.91 3.57-1.91z" fill="currentColor" fill-rule="nonzero"></path></g>
					</svg>
				</a>
			{% endif %}
			</button>
			<span class="pl-0.5">{{ post.likes.__len__() }}</span>
		</div>
		<div class="flex ml-auto">
			<button onclick="hide_comments({{ post.id }}); get_comments({{ post.id }});">
				<svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="M0 0h24v24H0z"></path><path d="M16.9 4H7.1c-1.15 0-1.73.11-2.35.44-.56.3-1 .75-1.31 1.31C3.11 6.37 3 6.95 3 8.1v5.8c0 1.15.11 1.73.44 2.35.3.56.75 1 1.31 1.31l.15.07c.51.25 1.04.35 1.95.37h.25v2.21c0 .44.17.85.47 1.16l.12.1c.64.55 1.6.52 2.21-.08L13.37 18h3.53c1.15 0 1.73-.11 2.35-.44.56-.3 1-.75 1.31-1.31.33-.62.44-1.2.44-2.35V8.1c0-1.15-.11-1.73-.44-2.35a3.17 3.17 0 0 0-1.31-1.31A4.51 4.51 0 0 0 16.9 4zM6.9 5.8h9.99c.88 0 1.18.06 1.5.23.25.13.44.32.57.57.17.32.23.62.23 1.5v6.16c-.02.61-.09.87-.23 1.14-.13.25-.32.44-.57.57-.32.17-.62.23-1.5.23h-4.02a.9.9 0 0 0-.51.26l-3.47 3.4V17.1c0-.5-.4-.9-.9-.9H6.74a2.3 2.3 0 0 1-1.14-.23 1.37 1.37 0 0 1-.57-.57c-.17-.32-.23-.62-.23-1.5V7.74c.02-.61.09-.87.23-1.14.13-.25.32-.44.57-.57.3-.16.58-.22 1.31-.23z" fill="currentColor" fill-rule="nonzero"></path></g></svg>
			</button>
			<span class="pl-0.5">{{ post.comments.__len__() }}</span>
		</div>
	</div>
	<div id="comment-wrapper-{{ post.id }}" class="flex flex-col gap-8 hidden mt-4">
		<form method="POST" action="">
			<input type="hidden" name="post_id" value="{{ post.id }}">
			<div class="flex gap-4">
				{{ post.cmnt_form.csrf_token }}
				{{ post.cmnt_form.content(style="min-height:40px;", class="flex-1 h-10 border-2 border-gray-200") }} 
				<button class="border-2 border-gray-200 text-sky-400 hover:cursor-pointer w-min h-10 items-center flex px-2">
					{% if current_user.is_authenticated %}
						{{ post.cmnt_form.submit(class="text-m hover:cursor-pointer") }} 
					{% else %}
						<a class="text-m hover:cursor-pointer" href="/login">
							Send
						</a>
					{% endif %}
				</button>
			</div>
		</form>
		<div id="comment-block-{{ post.id }}" class="flex flex-col gap-8">
		</div>
	</div>
</div>

flaskblog/templates/includes/post_pgtn.html
{% if pages != 1 %}
<div id="page_buttons" class="flex gap-4">
{% if page != 1 %}
<button class="border-2 border-gray-200 text-sky-400 hover:cursor-pointer w-min h-10 items-center flex px-6" onclick="set_params('page', {{ page-1 }})">
	prev_page
</button>
{% endif %}
{% if pages > 1 and page != pages %}
<button class="border-2 border-gray-200 text-sky-400 hover:cursor-pointer w-min h-10 items-center flex px-6" onclick="set_params('page', {{ page+1 }})">
	next_page
</button>
{% endif %}
</div>
{% endif %}

flaskblog/templates/includes/sort_buttons.html
<div id="sort_buttons" class="flex gap-4">
<button class="border-2 w-min h-10 items-center flex px-6
{% if params['order'] == 'desc' %}
border-gray-300 bg-gray-200 text-sky-500 
{% else %}
border-gray-200 text-sky-400" onclick="set_params('order', 'desc') 
{% endif %}
">⬇️</button>
<button class="border-2 w-min h-10 items-center flex px-6
{% if params['order'] == 'asc' %}
border-gray-300 bg-gray-200 text-sky-500 
{% else %}
border-gray-200 text-sky-400" onclick="set_params('order', 'asc') 
{% endif %}
">⬆️</button>
<span class="self-center">Sort by</span>
<button class="border-2 w-min h-10 items-center flex px-6
{% if params['sort'] == 'date' %}
border-gray-300 bg-gray-200 text-sky-500 
{% else %}
border-gray-200 text-sky-400" onclick="set_params('sort', 'date') 
{% endif %}
">date</button>

<button class="border-2 w-min h-10 items-center flex px-6
{% if params['sort'] == 'likes' %}
border-gray-300 bg-gray-200 text-sky-500 
{% else %}
border-gray-200 text-sky-400" onclick="set_params('sort', 'likes') 
{% endif %}
">likes</button>

<button class="border-2 w-min h-10 items-center flex px-6
{% if params['sort'] == 'comments' %}
border-gray-300 bg-gray-200 text-sky-500 
{% else %}
border-gray-200 text-sky-400" onclick="set_params('sort', 'comments') 
{% endif %}
">comments</button>

</div>

flaskblog/templates/includes/std_form.html
<div class="[&>*]:mb-4 focus-visible:[&>*>input]:border-gray-400 focus-visible:[&>*>input]:outline-none">
	{{ form.hidden_tag() }}
	{% for field in form._fields.values() %}
		{% if field.type == "SubmitField" %}
			<button class="border-2 border-gray-200 text-sky-400 mt-10 hover:cursor-pointer w-min h-10 items-center flex px-6">
				{{ field(class="text-l hover:cursor-pointer") }} 
			</button>
		{% elif field.type == "CSRFTokenField" %}
			{{ field }}
		{% else %}
			<div>
					{{ field.label(class="text-l pb-1") }} 
					{% if field.errors %}
						{% for error in field.errors %}
							{{ field(style="min-height:40px;", class="w-full h-10 border-2 border-red-400") }} 
							<span class="block pt-1 text-m text-red-400">{{ error }}</span>
						{% endfor %}
					{% else %}
						{{ field(style="min-height:40px;", class="w-full h-10 border-2 border-gray-200") }} 
					{% endif %}
			</div>
		{% endif %}
	{% endfor %}
</div>